package com.lld.design.linkedin;

public enum NotificationType {
	
	JOB_POSTING, MESSAGE, CONNECTION_REQUEST, ENDORSEMENT, COMMENT, LIKE, SHARE, FOLLOW, MENTION, GROUP_INVITATION, EVENT_INVITATION, NEWS_UPDATE, ARTICLE_PUBLISHED, PROFILE_VIEW;

}
